import { Event } from '../models/eventModel';
import { createDocument, getDocuments, 
    getDocumentById, updateDocument,
    deleteDocument } from "../repositories/firestoreRepository";

// Name of the Firestore collection for events
const COLLECTION = "events";

/**
 * Creates an event
 * @param eventData - The data to create an event with
 * @returns The event with a unique ID generated by firestore
 */
export const createEventService = async (
    eventData: {
        name: string;
        date: string;
        capacity: number;
        registrationCount?: number;
        status?: string;
        category?: string;
    }): Promise<Event> => 
{

    try 
    {
        // create a new event and automatically assign values to 
        // undefined fields and current timestamp to new events
        const newEvent: Event =
        {
            name: eventData.name,
            date: eventData.date,
            capacity: eventData.capacity,
            registrationCount: eventData.registrationCount || 0,
            status: eventData.status || "active",
            category: eventData.category || "general",
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        };

        const id = await createDocument<Event>(COLLECTION, newEvent);

        return { id, ...newEvent } as Event;
    } 
    catch (error: unknown) 
    {
        const errorMessage = error instanceof Error ? error.message : "Unknown error";
        throw new Error(`Failed to create event: ${errorMessage}`);
    }
};

/**
 * Gets all events
 * @returns The list of all events
 */
export const getAllEventsService = async (): Promise<Event[]> => 
{
    try 
    {
        const snapshot = await getDocuments(COLLECTION);

        const events = snapshot.docs.map((doc) => 
        {
            const data = doc.data();
            return {
                id: doc.id,
                name: data.name,
                date: data.date.toDate().toISOString(),
                capacity: data.capacity,
                registrationCount: data.registrationCount,
                status: data.status,
                category: data.category,
                createdAt: data.createdAt,
                updatedAt: data.updatedAt
            } as Event;
        });
        return events;
    } 
    catch (error: unknown)
    {
        const errorMessage = error instanceof Error ? error.message : "Unknown error";
        throw new Error(`Failed to retrieve all events: ${errorMessage}`);
    }
};

/**
 * Gets an event by ID
 * @param id - The event ID
 * @returns The event with the specified ID
 */
export const getEventService = async (id: string): Promise<Event> =>
{
    try 
    {
        const doc = await getDocumentById(COLLECTION, id);

        if (!doc) 
        {
            throw new Error(`Event with ID ${id} not found`);
        }

        const data = doc.data();

        const event: Event = {
            id: doc.id,
            name: data?.name,
            date: data?.date.toDate().toISOString(),
            capacity: data?.capacity,
            registrationCount: data?.registrationCount,
            status: data?.status,
            category: data?.category,
            createdAt: data?.createdAt,
            updatedAt: data?.updatedAt
        } as Event;

        return event;
    } 
    catch (error: unknown) 
    {
        const errorMessage = error instanceof Error ? error.message : "Unknown error";
        throw new Error(`Failed to retrieve the event: ${errorMessage}`);
    }

}

/**
 * Updates an Event
 * @param id - The ID of the event to be updated
 * @param eventData - The data to update the event with
 * @returns The updated event
 */
export const updateEventService = async (id: string, eventData: Partial<Pick<
    Event, "registrationCount" | "status">> ): Promise<Event> =>
{
    try 
    {
        // Remove undefined fields from data passed to update document
        // function, and validate registrationCount against event capacity
        const event = await getEventService(id);
        const data: Partial<Pick<Event, "registrationCount" | "status">> = {};

        if (eventData.registrationCount !== undefined) 
        {
            // Check that registrationCount does not exceed capacity
            if (eventData.registrationCount > event.capacity) 
            {
                throw new Error(`registrationCount (${eventData.registrationCount}) `
                    +`cannot exceed event capacity (${event.capacity})`);
            }
            data.registrationCount = eventData.registrationCount;
        }

        if (eventData.status !== undefined) 
        {
            data.status = eventData.status;
        }

        const updateData = {
            ...data,
            updatedAt: new Date().toISOString(),
        };
        
        await updateDocument<Event>(COLLECTION, id, updateData);

        // Return the updated event
        const updatedEvent = await getEventService(id);
        return updatedEvent;
    } 
    catch (error: unknown)
    {
        const errorMessage =error instanceof Error ? error.message : "Unknown error";
        throw new Error(`Failed to update event ${id}: ${errorMessage}`);
    }
};

/**
 * Deletes an Event
 * @param id - The ID of the event to be deleted
 * @returns Nothing
 */
export const deleteEventService = async (id: string): Promise<void> =>
{
    try 
    {
        // Check if event exists before deleting
        const event = await getEventService(id);
        if (!event) 
        {
            throw new Error(`Event with ID ${id} not found`);
        }

        await deleteDocument(COLLECTION, id);
    } 
    catch (error: unknown)
    {
        const errorMessage = error instanceof Error ? error.message : "Unknown error";
        throw new Error(`Failed to delete the event: ${errorMessage}`);
    }
}